project:
  type: website
  output-dir: docs

website:
  title: "Joshua Paul Cohen"
  #favicon: website_icon_cropped.png
  navbar:
    logo: website_icon_cropped.PNG
    title: false
    logo-alt: "cute silk moth"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - href: MEDS_Master_Resume.pdf
        text: Resume
      - href: posts.qmd
        text: Posts
  page-footer:
    background: light
    left: No Copyright, Feel free to distribute.
    right: This website is built with {{< fa brands github title="the octocat github icon">}}

format:
  html:
    theme: styles.scss
    mainfont: Fauna One
    toc: false
    page-layout: full

editor: source

