project:
  type: website
  output-dir: docs

website:
  title: "Joshua Paul Cohen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: false
    page-layout: full

editor: visual

